config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get '/dashboard', to: "base#dashboard"
    resources :orders, only: [:index, :update, :show]
    resources :items, only: [:index, :edit, :update]
  end

  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :create, :destroy, :update]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :create]
  resources :categories, only: [:index]
  get    '/dashboard',          to: "base#dashboard"
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
	patch  '/cart/add',           to: "carts#add"
	patch	 '/cart/subtract',      to: "carts#subtract"
  get    "/auth/google_oauth2/callback", to: "sessions#create"

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: "home#show"
  get    '/:title',        to: 'categories#show'
end

app/models/cart.rb
class Cart
  include ActiveModel::Model
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def items
    @contents.map do |item_id, quantity|
      Item.find_by(id: item_id.to_i)
    end
  end

	def total
		total = @contents.map do |item_id, quantity|
			Item.find(item_id.to_i).price * quantity
		end.sum
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    id = params["item_id"].to_s
    @item = Item.find_by(id: id)
    session[:cart] ||= Hash.new(0)
    session[:cart][id] = (session[:cart][id] || 0) + 1
    flash[:notice] = "Successfully add item to your cart."
    redirect_to items_path
  end

  def show
    @cart = Cart.new(session[:cart])
  end

  def update
		quantity = params["item"]["quantity"]
		id = params[:item_id]
		session[:cart][id] = quantity.to_i
		redirect_to '/cart'
  end

  def destroy
    item = Item.find(params[:item_id].to_i)
    session[:cart].delete(params[:item_id])
    flash[:notice] = %Q[Successfully removed <a href="/items/#{item.id}">#{item.title}</a> from your cart.]
    redirect_to cart_path
  end

	def add
		value = session[:cart][params["item_id"]]
		session[:cart][params["item_id"]] = value + 1
    redirect_to cart_path
	end

	def subtract
		value = session[:cart][params["item_id"]]
		session[:cart][params["item_id"]] = value - 1
		if session[:cart][params["item_id"]] == 0
			session[:cart].delete(params[:item_id])
		end
    redirect_to cart_path
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%=form_tag(cart_path, method: :put) do %>
	<%= label_tag "Quantity" %>
	<%= hidden_field_tag("item_id", item.id)%>
	<%= text_field_tag "item[quantity]" %>
	<%= submit_tag (value = "Submit") %>
<%end%>

app/views/carts/show.html.erb
<h1>Welcome to your cart!</h1>

<table class="table">
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Remove</th>
  </tr>
  <% set_cart.items.each do |item| %>
  <tr>
    <td><%= image_tag item.image, size: "30x30" %></td>
    <td><%= item.title %></td>
    <td><%= item.description %></td>
    <td><%= number_to_currency(item.price) %></td>
    <td>
      <div class="quantity">
        <%= button_to "+", cart_add_path(item_id: item.id), method: :patch%>
        <%= set_cart.contents[item.id.to_s] %>
        <%= button_to "-", cart_subtract_path(item_id: item.id), method: :patch%>
      </div>
    </td>
    <td><%= link_to "Remove", cart_path(item_id: item.id), method: :delete %></td>
  </tr>
  <% end %>
</table>

<h3>Total Price: <%=number_to_currency(@cart.total)%></h3>
<br>
  <% if current_user %>
		<h4 class="only"><button href="/orders"><%= link_to "Checkout", orders_path, method: "post" %></button></h4>
  <% else %>
	  <h4 class="only_1"><button href="/login"><%= link_to "Login or Create Account to Checkout", login_path %></button</h4>
  <% end %>