config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get '/dashboard', to: "base#dashboard"
    resources :orders, only: [:index, :update, :show]
    resources :items, only: [:index, :edit, :update]
  end

  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :create, :destroy, :update]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :create]
  resources :categories, only: [:index]
  get    '/dashboard',          to: "base#dashboard"
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
	patch  '/cart/add',           to: "carts#add"
	patch	 '/cart/subtract',      to: "carts#subtract"
  get    "/auth/google_oauth2/callback", to: "sessions#create"

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: "home#show"
  get    '/:title',        to: 'categories#show'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :items

  before_save :add_slug

  def add_slug
    self.slug = self.title.parameterize
  end

  def average_price
    items.average(:price)
  end

  def active?
    items.where(status: "active").count
  end

  def retired?
    items.where(status: "retired").count
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(title: params[:title])
    @category.slug
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find_by(title: params[:title])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="category-index">
  <% @categories.each do |category| %>
    <h1><%= link_to category.title, "/#{category.title}"%></h1>
    <table class="table">
      <tr>
        <th>Amount of Items</th>
        <th>Average Price</th>
        <th>Active</th>
        <th>Retired</th>
      </tr>
      <tr>
        <td><%= category.items.count %></td>
        <td><%= number_to_currency(category.average_price)%></td>
        <td><%= category.active? %></td>
        <td><%= category.retired? %></td>
      </tr>

    </table>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.title %>s</h1>
<section class="items">
<% @category.items.each do |item| %>
<div class="items-index">
	<%= image_tag item.image%>
  <div class="container">
		<h3>Title: <%= link_to item.title, item_path(item) %></h3>
		<h3>Description: <%= item.description %></h3>
		<h3>Price: <%= item.price %></h3>
		<% if item.active? %>
		<h4><%= link_to "Add to Cart", cart_path(item_id: item.id), method: :post %></h4>
		<% else %>
		<h4>Item Retired</h4>
		<% end %>
  </div>
</div>
<% end %>
</section>