config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  namespace :admin do
    get '/dashboard', to: "base#dashboard"
    resources :orders, only: [:index, :update, :show]
    resources :items, only: [:index, :edit, :update]
  end

  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :create, :destroy, :update]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :create]
  resources :categories, only: [:index]
  get    '/dashboard',          to: "base#dashboard"
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
	patch  '/cart/add',           to: "carts#add"
	patch	 '/cart/subtract',      to: "carts#subtract"
  get    "/auth/google_oauth2/callback", to: "sessions#create"

  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: "home#show"
  get    '/:title',        to: 'categories#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  include ActiveModel::Model
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def items
    @contents.map do |item_id, quantity|
      Item.find_by(id: item_id.to_i)
    end
  end

	def total
		total = @contents.map do |item_id, quantity|
			Item.find(item_id.to_i).price * quantity
		end.sum
	end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :items

  before_save :add_slug

  def add_slug
    self.slug = self.title.parameterize
  end

  def average_price
    items.average(:price)
  end

  def active?
    items.where(status: "active").count
  end

  def retired?
    items.where(status: "retired").count
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :orders_items
  has_many :orders, through: :orders_items
  validates_presence_of :title, :description, :price

  validates :title, uniqueness: true
  validates :price, numericality: {greater_than_or_equal_to: 0}

	enum status: [:active, :retired]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orders_items
  has_many :items, through: :orders_items

  enum status: [:ordered, :paid, :cancelled, :completed]

  def total
    items.sum(:price)
  end

  def quantity(id)
    item_ids.count(id)
  end

  def subtotal(item)
    item.price * quantity(item.id)
  end
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders

  enum role: [:default, :admin]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :current_user?

  def dashboard
    @user = User.find(session[:user_id])
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    id = params["item_id"].to_s
    @item = Item.find_by(id: id)
    session[:cart] ||= Hash.new(0)
    session[:cart][id] = (session[:cart][id] || 0) + 1
    flash[:notice] = "Successfully add item to your cart."
    redirect_to items_path
  end

  def show
    @cart = Cart.new(session[:cart])
  end

  def update
		quantity = params["item"]["quantity"]
		id = params[:item_id]
		session[:cart][id] = quantity.to_i
		redirect_to '/cart'
  end

  def destroy
    item = Item.find(params[:item_id].to_i)
    session[:cart].delete(params[:item_id])
    flash[:notice] = %Q[Successfully removed <a href="/items/#{item.id}">#{item.title}</a> from your cart.]
    redirect_to cart_path
  end

	def add
		value = session[:cart][params["item_id"]]
		session[:cart][params["item_id"]] = value + 1
    redirect_to cart_path
	end

	def subtract
		value = session[:cart][params["item_id"]]
		session[:cart][params["item_id"]] = value - 1
		if session[:cart][params["item_id"]] == 0
			session[:cart].delete(params[:item_id])
		end
    redirect_to cart_path
	end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find_by(title: params[:title])
  end
end

app/controllers/items_controller.rb
require "will_paginate"
class ItemsController < ApplicationController
  def index
    @items = Item.paginate(page: params[:page], per_page: 30)
  end

	def show
		 @item = Item.find(params[:id])
	end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

	def create
		order = current_user.orders.new()
		session[:cart].each do |key, value|
			value.times do
				order.items << Item.find(key.to_i)
      end
		end
		order.save
		flash[:notice] = "Order was successfully placed"
		session.delete(:cart)
		redirect_to orders_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user?, except: [:new, :create, :auth]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
      flash[:notice] = "Logged in as #{@user.username}"
    else
      render :new
    end
  end

	def edit
		@user = User.find(current_user.id)

    if @user.id != params[:id].to_i
        render file: "/public/404"
    end
	end

	def update
		user = User.find(current_user.id)
		user.update(user_params)

		if user.save
			flash[:notice] = "Account Information Updated!"
			redirect_to '/dashboard'
		else
			flash[:notice] = "Something Went Wrong! Try Again!"
			render :edit
		end
  end
  
  def auth
    byebug
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Little Nightmares</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="title">
      <div class="icon">
        <%= image_tag ("crescent-moon.png") %>
        <h1>Little Nightmares</h1>
      </div>
      <div class="order-header">
        <h1> <%= link_to "Orders", admin_orders_path if current_admin? %></h1>
        <h1> <%= link_to "Orders", orders_path if session[:user_id] && !current_admin? %></h1>
        <h1> <%= link_to "Admin Dashboard", admin_dashboard_path if current_admin? %></h1>
        <h1> <%= link_to "Dashboard", dashboard_path if session[:user_id] && !current_admin?%> </h1>
        <% if current_user %>
        <h1><%= link_to "Logout", logout_path, method: :delete %></h1>
        <% else %>
        <h1><%= link_to "Login", login_path %></h1>
        <% end %>
      </div>
    </header>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <% if current_admin? %>
        <li><%= link_to "Items", admin_items_path %></li>
        <% else %>
        <li><%= link_to "Items", items_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropbtn"><%= link_to "Categories", '/categories' %></a>
          <div class="dropdown-content">
            <% categories.each do |category| %>
            <%= link_to category.title, "/#{category.title}" %>
            <% end %>
          </div>
        </li>
        <li><%= link_to "View Cart", "/cart" %></li>

  <div class="w3-container">
    <button onclick="document.getElementById('id01').style.display='block'" class="w3-button">
      <h3><%= session[:cart].values.sum unless session[:cart].nil? %></h3>
      <%= image_tag ("cart.png"), size: "30x30" %>
    </button>
    <div id="id01" class="w3-modal w3-animate-opacity">
      <div class="w3-modal-content w3-card-4">
        <header class="w3-container w3-teal">
          <span onclick="document.getElementById('id01').style.display='none'"
          class="w3-button w3-large w3-display-topright">&times;</span>
          <h2>Your Cart</h2>
        </header>
        <div class="w3-container">
            <table style="width:100%">
              <tr>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Remove</th>
              </tr>
              <% set_cart.items.each do |item| %>
              <tr>
                <td><%= image_tag item.image, size: "30x30" %></td>
                <td><%= item.title %></td>
                <td><%= item.description %></td>
                <td><%= number_to_currency(item.price) %></td>
              	<td class="quantity">
                    <%= button_to "+", cart_add_path(item_id: item.id), method: :patch%>
                    <%= set_cart.contents[item.id.to_s] %>
                    <%= button_to "-", cart_subtract_path(item_id: item.id), method: :patch%>
                </td>
                <td><%= link_to "Remove", cart_path(item_id: item.id), method: :delete %></td>
              </tr>
              <% end %>
            </table>
        </div>
        <footer class="w3-container w3-teal">
          <% if current_user %>
            <h4><%= link_to"Checkout", orders_path, method: "post" %></h4>
          <% else %>
            <h4><%= link_to "Login or Create Account to Checkout", login_path %></h4>
          <% end %>
        </footer>
      </div>
    </div>
  </div>
</ul>
  <% flash.each do |type, message| %>
	<div class="green-flash">
    	<p><%= sanitize(message) %></p>
  </div>
 <% end %>
    <%= yield %>
  </body>
</html>